#!/usr/bin/env node
/**
 * content/regenerate.mjs — refresh (or verify) the Markdown mirror in
 * content/pages/ from the built HTML in dist/.
 *
 * The body of every content/pages/**.md file between the BEGIN/END MIRROR
 * markers is produced by `htmlToMarkdown()` from build/lib/artifacts.mjs — the
 * SAME function build/sync.mjs uses to produce llms-full.txt. Nothing in the
 * mirror is hand-written, so the mirror cannot drift from the pages: this
 * script re-derives it and fails when the file on disk disagrees.
 *
 * Everything OUTSIDE the markers — the YAML front-matter and the
 * "Content review" section at the foot of each file — is editorial and is
 * preserved verbatim by --write.
 *
 *   node content/regenerate.mjs                 # check; report drift; exit 0
 *   node content/regenerate.mjs --strict        # check; exit 1 on any drift
 *   node content/regenerate.mjs --write         # rewrite the mirror blocks
 *   node content/regenerate.mjs --write --only gpo-purchasing
 *   node content/regenerate.mjs --src DIR       # read pages from DIR, not dist/
 *
 * Zero dependencies. ESM. Node >= 18.
 *
 * NOTE ON llms.txt / llms-full.txt: those files, like these mirrors, are for
 * third-party AI crawlers and for content review. Google Search does not read
 * them and they have no effect on Google ranking or indexing.
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { htmlToMarkdown } from '../build/lib/artifacts.mjs';
import { site, routes } from '../site.config.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const PAGES = path.join(ROOT, 'content', 'pages');

const BEGIN =
  '<!-- BEGIN MIRROR — generated by content/regenerate.mjs via build/lib/artifacts.mjs htmlToMarkdown(). Do not hand-edit. -->';
const END = '<!-- END MIRROR -->';

/* ------------------------------------------------------------------ *
 * Source resolution
 * ------------------------------------------------------------------ */

/** Where the built pages live (what the mirror must match). */
function defaultSrcDir() {
  return path.join(ROOT, 'dist');
}

/**
 * The pre-build export, used only for the `hidden` backfill described below.
 * Same candidate list build/sync.mjs uses. Optional: when it is absent the
 * backfill is skipped and the affected sections stay empty.
 */
function exportDir() {
  const candidates = [
    path.join(ROOT, 'src', 'source-export'),
    '/tmp/claude-0/-home-user-test/da065df0-1665-52a8-b803-716d1ee66e9a/scratchpad/src/source-export',
  ];
  return candidates.find((dir) => existsSync(path.join(dir, 'index.html'))) || null;
}

/** '/services/lab-solutions/' -> 'services/lab-solutions/index.html' */
function htmlFileFor(route) {
  return route.path === '/' ? 'index.html' : route.path.replace(/^\//, '') + 'index.html';
}

/** '/' -> 'index.md'; '/404/' -> '404.md'; '/a/b/' -> 'a/b.md' */
export function markdownFileFor(route) {
  if (route.path === '/') return 'index.md';
  return route.path.replace(/^\//, '').replace(/\/$/, '') + '.md';
}

/* ------------------------------------------------------------------ *
 * Deterministic normalisation of the raw htmlToMarkdown() output
 * ------------------------------------------------------------------ */

/**
 * 1. Drop a leading visible-breadcrumb line ("[Home](/) › Laboratory
 *    Solutions"). It is site navigation the SSR chrome renders, not page
 *    content, and it is already carried by `parent` in the front-matter.
 */
function dropBreadcrumb(md) {
  return md.replace(/^\s*\[Home\]\(\/\)[^\n]*›[^\n]*\n+/, '');
}

/**
 * 2. Collapse a line that is immediately repeated. The timeline on /about/ and
 *    several stat rows print the same label twice (one copy per breakpoint);
 *    both copies are the same DOM text, so the duplicate carries no content.
 */
function collapseAdjacentDuplicates(md) {
  const out = [];
  let lastMeaningful = null;
  for (const line of md.split('\n')) {
    const t = line.trim();
    if (t === '') {
      out.push(line);
      continue;
    }
    if (t === lastMeaningful) continue; // duplicate of the previous non-blank line
    lastMeaningful = t;
    out.push(line);
  }
  return out.join('\n').replace(/\n{3,}/g, '\n\n');
}

/**
 * 4. Drop a short label line that echoes one emitted a few lines earlier. The
 *    /about/ timeline prints each milestone's year twice — once before the
 *    heading and once after the body — so the second copy is a duplicate of a
 *    value already carried. Scoped deliberately: a line of at most 16
 *    characters, containing no Markdown syntax, that repeats one of the last
 *    six meaningful lines. Measured effect across all 21 pages: three lines on
 *    /about/ ("2005", "2012", "2020") and nothing anywhere else.
 */
function dropShortEcho(md) {
  const out = [];
  const recent = [];
  for (const line of md.split('\n')) {
    const t = line.trim();
    if (t === '') {
      out.push(line);
      continue;
    }
    const plainShortLabel = t.length <= 16 && !/[[\]()!*_`|#>-]/.test(t);
    if (plainShortLabel && recent.slice(-6).includes(t)) continue;
    recent.push(t);
    out.push(line);
  }
  return out.join('\n').replace(/\n{3,}/g, '\n\n');
}

/**
 * 3. Backfill sections the BUILT page hides behind the `hidden` attribute.
 *
 *    The fix-a11y pass collapses FAQ answers with `hidden` (correct: it takes
 *    them out of the accessibility tree and the tab order), and
 *    htmlToMarkdown() drops `hidden` subtrees (also correct: it must not emit
 *    invisible text). The two together delete five of the six answers on / from
 *    any Markdown derived from the built page — including llms-full.txt.
 *
 *    Here we restore them from the pre-collapse export, matching on the exact
 *    question text. Nothing is invented: the text comes from the export's own
 *    HTML, converted by the same function.
 */
function backfillHiddenSections(builtMd, exportMd) {
  if (!exportMd) return builtMd;

  const builtLines = builtMd.split('\n');
  const headingTexts = new Set(
    builtLines.filter((l) => /^#{1,6}\s/.test(l)).map((l) => l.replace(/^#+\s*/, '').trim())
  );

  const exportLines = exportMd.split('\n');
  const firstSeen = new Map();
  exportLines.forEach((line, i) => {
    const t = line.trim();
    if (t !== '' && !firstSeen.has(t)) firstSeen.set(t, i);
  });

  const out = [];
  for (let i = 0; i < builtLines.length; i++) {
    const line = builtLines[i];
    out.push(line);

    const m = /^(#{2,6})\s+(.+)$/.exec(line);
    if (!m) continue;

    // Section is "empty" when the next non-blank line is another heading.
    let empty = true;
    for (let j = i + 1; j < builtLines.length; j++) {
      if (/^#{1,6}\s/.test(builtLines[j])) break;
      if (builtLines[j].trim() !== '') {
        empty = false;
        break;
      }
    }
    if (!empty) continue;

    const at = firstSeen.get(m[2].trim());
    if (at === undefined) continue;

    const grabbed = [];
    for (let k = at + 1; k < exportLines.length; k++) {
      const t = exportLines[k].trim();
      if (/^#{1,6}\s/.test(t)) break; // next heading in the export
      if (t !== '' && headingTexts.has(t)) break; // next question/heading of the built page
      grabbed.push(exportLines[k]);
    }
    while (grabbed.length && grabbed[0].trim() === '') grabbed.shift();
    while (grabbed.length && grabbed[grabbed.length - 1].trim() === '') grabbed.pop();
    if (grabbed.length === 0) continue;

    out.push('', ...grabbed);
  }

  return out.join('\n').replace(/\n{3,}/g, '\n\n');
}

/** The full mirror body for one route. */
export function mirrorFor(route, opts) {
  const srcDir = opts.srcDir;
  const htmlPath = path.join(srcDir, htmlFileFor(route));
  if (!existsSync(htmlPath)) return null;

  const built = htmlToMarkdown(readFileSync(htmlPath, 'utf8'));

  let exportMd = null;
  const expDir = opts.exportDir;
  if (expDir) {
    const expPath = path.join(expDir, htmlFileFor(route));
    if (existsSync(expPath)) exportMd = htmlToMarkdown(readFileSync(expPath, 'utf8'));
  }

  let md = backfillHiddenSections(built, exportMd);
  md = dropBreadcrumb(md);
  md = collapseAdjacentDuplicates(md);
  md = dropShortEcho(md);
  return md.trim() + '\n';
}

/* ------------------------------------------------------------------ *
 * File assembly
 * ------------------------------------------------------------------ */

function yamlString(value) {
  return '"' + String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
}

function frontMatter(route, byId) {
  const parent = route.parent ? byId.get(route.parent) : null;
  const lines = [
    '---',
    `title: ${yamlString(route.title)}`,
    `path: ${route.path}`,
    `canonical: ${site.origin}${route.path}`,
    `description: ${yamlString(route.description)}`,
    `group: ${route.group}`,
    `parent: ${parent ? parent.path : 'null'}`,
    'keywords:',
    ...route.keywords.map((k) => `  - ${yamlString(k)}`),
    `summary: ${yamlString(route.summary)}`,
    `lastReviewed: ${new Date().toISOString().slice(0, 10)}`,
    '---',
  ];
  return lines.join('\n');
}

function newFile(route, byId, body) {
  return [
    frontMatter(route, byId),
    '',
    BEGIN,
    '',
    body.trim(),
    '',
    END,
    '',
    '---',
    '',
    '## Content review',
    '',
    'Editorial metadata — not page content, and not part of the mirror above.',
    '',
    '- No pending corrections recorded for this page.',
    '',
  ].join('\n');
}

/** Replace only the mirror block; keep front-matter and the review section. */
function replaceMirror(existing, body) {
  const b = existing.indexOf(BEGIN);
  const e = existing.indexOf(END);
  if (b === -1 || e === -1 || e < b) return null;
  return existing.slice(0, b + BEGIN.length) + '\n\n' + body.trim() + '\n\n' + existing.slice(e);
}

function currentMirror(existing) {
  const b = existing.indexOf(BEGIN);
  const e = existing.indexOf(END);
  if (b === -1 || e === -1 || e < b) return null;
  return existing.slice(b + BEGIN.length, e).trim() + '\n';
}

/* ------------------------------------------------------------------ *
 * CLI
 * ------------------------------------------------------------------ */

function parseArgs(argv) {
  const opts = { write: false, strict: false, only: null, src: null };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--write') opts.write = true;
    else if (a === '--strict') opts.strict = true;
    else if (a === '--only') opts.only = argv[++i];
    else if (a.startsWith('--only=')) opts.only = a.slice(7);
    else if (a === '--src') opts.src = path.resolve(process.cwd(), argv[++i]);
    else if (a.startsWith('--src=')) opts.src = path.resolve(process.cwd(), a.slice(6));
    else if (a === '--help' || a === '-h') opts.help = true;
    else throw new Error(`unknown argument: ${a}`);
  }
  return opts;
}

function main() {
  const opts = parseArgs(process.argv.slice(2));
  if (opts.help) {
    process.stdout.write(
      'usage: node content/regenerate.mjs [--write] [--strict] [--only ROUTE_ID] [--src DIR]\n'
    );
    return 0;
  }

  const srcDir = opts.src || defaultSrcDir();
  if (!existsSync(path.join(srcDir, 'index.html'))) {
    process.stderr.write(
      `content/regenerate.mjs: no built pages at ${srcDir}\n` +
        '  run `node build/sync.mjs` first, or pass --src DIR\n'
    );
    return 2;
  }
  const expDir = exportDir();

  const byId = new Map(routes.map((r) => [r.id, r]));
  const rows = [];

  for (const route of routes) {
    if (opts.only && route.id !== opts.only) continue;

    const file = path.join(PAGES, markdownFileFor(route));
    const body = mirrorFor(route, { srcDir, exportDir: expDir });
    if (body === null) {
      rows.push({ id: route.id, state: 'NO HTML' });
      continue;
    }

    if (!existsSync(file)) {
      if (opts.write) {
        mkdirSync(path.dirname(file), { recursive: true });
        writeFileSync(file, newFile(route, byId, body), 'utf8');
        rows.push({ id: route.id, state: 'created' });
      } else {
        rows.push({ id: route.id, state: 'MISSING' });
      }
      continue;
    }

    const existing = readFileSync(file, 'utf8');
    const current = currentMirror(existing);
    if (current === null) {
      rows.push({ id: route.id, state: 'NO MARKERS' });
      continue;
    }

    if (current === body) {
      rows.push({ id: route.id, state: 'ok' });
      continue;
    }

    if (opts.write) {
      const next = replaceMirror(existing, body);
      writeFileSync(file, next, 'utf8');
      rows.push({ id: route.id, state: 'updated' });
    } else {
      const a = current.split('\n');
      const b = body.split('\n');
      let differing = 0;
      for (let i = 0; i < Math.max(a.length, b.length); i++) if (a[i] !== b[i]) differing++;
      rows.push({ id: route.id, state: `DRIFT (${differing} lines)` });
    }
  }

  const width = rows.reduce((m, r) => Math.max(m, r.id.length), 0);
  for (const r of rows) process.stdout.write(`  ${r.id.padEnd(width)}  ${r.state}\n`);

  const bad = rows.filter((r) => /^(DRIFT|MISSING|NO )/.test(r.state));
  process.stdout.write(
    `\n  ${rows.length} routes · ${rows.length - bad.length} in sync · ${bad.length} needing attention\n`
  );
  if (!expDir) {
    process.stdout.write(
      '  note: source export not found — `hidden` sections (the collapsed FAQ answers on /) were not backfilled\n'
    );
  }
  return opts.strict && bad.length > 0 ? 1 : 0;
}

process.exitCode = main();
