"""Report rendering: full screening report as Markdown or JSON, plus a
compact ranking table for multi-resume runs."""

from __future__ import annotations

import json
from dataclasses import asdict
from typing import Dict, List

from . import taxonomy
from .feedback import Finding
from .jobspec import JobSpec
from .parser import ParsedResume
from .platforms import Decision
from .scoring import ScoreCard

_STATUS_EMOJI = {"ADVANCE": "✅", "HUMAN REVIEW": "🟡", "REJECT": "❌"}
_SEV_EMOJI = {"critical": "🔴", "warning": "🟠", "info": "🔵"}


def _cell(value) -> str:
    """Escape a dynamic value for use inside a Markdown table cell."""
    return str(value).replace("|", "\\|").replace("\n", " ")

SUBSCORE_LABELS = {
    "required_skills": "Required keywords",
    "preferred_skills": "Preferred keywords",
    "title": "Job-title alignment",
    "experience": "Years of experience",
    "education": "Education",
    "formatting": "Formatting & parseability",
}


def render_markdown(resume: ParsedResume, spec: JobSpec, card: ScoreCard,
                    decisions: List[Decision], findings: List[Finding]) -> str:
    out: List[str] = []
    name = resume.contact.name or "Candidate"
    out.append(f"# ATS Screening Report — {name}")
    out.append("")
    out.append(f"**Target role:** {spec.title}")
    out.append(f"**Resume source:** `{resume.source}`")
    out.append("")

    # --- headline score & decisions ---
    out.append(f"## Overall match score: {card.composite:g} / 100")
    out.append("")
    for d in decisions:
        emoji = _STATUS_EMOJI.get(d.status, "•")
        out.append(f"- {emoji} **{d.platform}** → **{d.status}** — {d.label}")
        for reason in d.reasons:
            out.append(f"  - {reason}")
    out.append("")

    # --- sub-scores ---
    out.append("## Score breakdown")
    out.append("")
    out.append("| Criterion | Score | Weight |")
    out.append("|---|---:|---:|")
    weights = card.weights
    for key, label in SUBSCORE_LABELS.items():
        if key in card.subscores:
            out.append(f"| {label} | {card.subscores[key]:g} | "
                       f"{weights.get(key, 0) * 100:g}% |")
    out.append(f"| **Composite** | **{card.composite:g}** | |")
    out.append("")

    # --- keywords ---
    out.append("## Keyword analysis")
    out.append("")
    out.append("| Keyword | Type | Found | In experience section |")
    out.append("|---|---|---|---|")
    for m in card.keyword_matches:
        kind = "Required" if m.required else "Preferred"
        found = "✅" if m.found else "❌ missing"
        in_exp = "✅" if m.in_experience else ("—" if not m.found else "list/summary only")
        out.append(f"| {m.display} | {kind} | {found} | {in_exp} |")
    out.append("")

    # --- parsed snapshot ---
    out.append("## What the ATS parser extracted")
    out.append("")
    c = resume.contact
    out.append(f"- **Name:** {c.name or '⚠️ not detected'}")
    out.append(f"- **Email:** {c.email or '⚠️ not detected'}")
    out.append(f"- **Phone:** {c.phone or '⚠️ not detected'}")
    out.append(f"- **LinkedIn:** {c.linkedin or 'not detected'}")
    sections = [s for s in resume.sections if s != "_header" and resume.sections[s]]
    out.append(f"- **Sections recognized:** {', '.join(sorted(sections)) or 'none'}")
    out.append(f"- **Job titles identified:** "
               f"{'; '.join(resume.titles) if resume.titles else '⚠️ none'}")
    out.append(f"- **Total parseable experience:** "
               f"{resume.total_experience_years:g} years "
               f"({len(resume.date_ranges)} dated role(s))")
    out.append(f"- **Highest degree detected:** "
               f"{resume.degrees[0] if resume.degrees else '⚠️ none'}")
    skills = ", ".join(sorted(taxonomy.display_name(s) for s in resume.skills_found))
    out.append(f"- **Skills recognized ({len(resume.skills_found)}):** {skills}")
    out.append("")

    # --- findings ---
    out.append("## Flagged issues & feedback")
    out.append("")
    if not findings:
        out.append("No issues flagged. 🎉")
    for f in findings:
        emoji = _SEV_EMOJI.get(f.severity, "•")
        out.append(f"### {emoji} {f.severity.upper()} · {f.category}")
        out.append("")
        out.append(f.message)
        out.append("")
        out.append(f"> **Fix:** {f.recommendation}")
        out.append("")

    # --- action list ---
    actions = [f for f in findings if f.severity in ("critical", "warning")]
    if actions:
        out.append("## Prioritized action list")
        out.append("")
        for i, f in enumerate(actions, 1):
            out.append(f"{i}. **[{f.severity}]** {f.recommendation}")
        out.append("")

    out.append("---")
    out.append("*Generated by ats-demo — a simulation for education. Real ATS "
               "platforms parse, search, and rank; genuine auto-rejection "
               "comes from employer-configured knockout questions, not hidden "
               "keyword scores. See README for details.*")
    return "\n".join(out)


def render_json(resume: ParsedResume, spec: JobSpec, card: ScoreCard,
                decisions: List[Decision], findings: List[Finding]) -> str:
    payload: Dict = {
        "candidate": asdict(resume.contact),
        "target_role": spec.title,
        "composite_score": card.composite,
        "subscores": card.subscores,
        "weights": card.weights,
        "decisions": [asdict(d) for d in decisions],
        "keywords": [
            {"skill": m.display, "required": m.required, "found": m.found,
             "in_experience": m.in_experience}
            for m in card.keyword_matches
        ],
        "parsed": {
            "sections": sorted(s for s in resume.sections
                               if s != "_header" and resume.sections[s]),
            "titles": resume.titles,
            "total_experience_years": resume.total_experience_years,
            "employment_gaps": resume.employment_gaps,
            "degrees": resume.degrees,
            "skills_found": sorted(resume.skills_found),
            "word_count": resume.word_count,
        },
        "findings": [asdict(f) for f in findings],
    }
    return json.dumps(payload, indent=2, ensure_ascii=False)


def render_ranking(job_title: str, rows: List[Dict]) -> str:
    """rows: [{name, source, composite, status, missing_required}, ...]
    already sorted best-first."""
    out = [f"# Ranking for: {job_title}", ""]
    out.append("| Rank | Candidate | Score | Decision | Missing required keywords |")
    out.append("|---:|---|---:|---|---|")
    for i, r in enumerate(rows, 1):
        missing = _cell(", ".join(r["missing_required"])) or "—"
        out.append(f"| {i} | {_cell(r['name'])} (`{_cell(r['source'])}`) "
                   f"| {r['composite']:g} "
                   f"| {_STATUS_EMOJI.get(r['status'], '')} {r['status']} | {missing} |")
    out.append("")
    return "\n".join(out)
